# Generated by Django 4.1.3 on 2025-01-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='tour',
            new_name='tour_id',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='date_id',
        ),
    ]
