# Generated by Django 4.2.16 on 2025-02-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0002_location_coordinates_alter_location_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='user_id',
            new_name='user',
        ),
    ]
