# Generated by Django 4.2.16 on 2025-01-29 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0002_rename_tour_itinerary_tour_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='tour',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
