# Generated by Django 4.2.16 on 2025-02-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0002_alter_location_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='uid',
            field=models.CharField(default='default_uid', max_length=50),
            preserve_default=False,
        ),
    ]
