# Generated by Django 4.2.16 on 2025-01-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0003_tour_duration_tour_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
