# Generated by Django 4.2.16 on 2025-02-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0003_rename_user_id_itinerary_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='user',
            new_name='user_id',
        ),
    ]
