# Generated by Django 4.2.16 on 2025-01-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0004_alter_tour_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
