# Generated by Django 4.2.16 on 2025-01-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0005_alter_tour_date_alter_tour_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time',
            field=models.TimeField(),
        ),
    ]
