# Generated by Django 4.2.16 on 2025-02-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0006_alter_tour_date_alter_tour_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='uid',
            field=models.CharField(default='default_uid', max_length=50),
            preserve_default=False,
        ),
    ]
