# Generated by Django 4.2.17 on 2025-02-05 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swelocaltoursapi', '0008_tour_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours_booked', to='swelocaltoursapi.user'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours_created', to='swelocaltoursapi.user'),
        ),
    ]
